services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.19
    container_name: mysql
    environment:
      - TZ=Asia/Taipei
      - MYSQL_DATABASE=clock_in_out_system
      - MYSQL_USER=sys_admin
      - MYSQL_PASSWORD=MySQLPassword
      - MYSQL_ROOT_PASSWORD=MySQLRootPassword
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --default-authentication-plugin=mysql_native_password
  backend:
    build:
      context: ./
    container_name: clock-in-out-system
    env_file:
      - .env.docker
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3307
    depends_on:
      - db
volumes:
  db: {}
